FROM node:20.1.0

# Create and set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of your application code to the working directory
COPY . .

# Expose the port your Express app will run on
EXPOSE 5000

# Define the command to run your application
CMD ["node", "server.js"]
